#!/usr/bin/env python3
"""Time 1024-chunk world generation: Cinder vs Pumpkin.

Both run a vanilla-style Full pipeline on a 32×32 grid (biomes, 3D
density, aquifers, surface, carvers, ores/trees, lighting). Cinder
evaluates vanilla 26.2 overworld.json density functions natively.
"""
from __future__ import annotations

import json
import os
import signal
import statistics
import subprocess
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BENCH = ROOT / "bench"
CINDER = ROOT / "cinder"
PUMPKIN_GEN = Path("/home/nataxcan/dev/Pumpkin/target/release/pumpkin-gen")
OUT = BENCH / "world_results.json"


def kill_tree(proc: subprocess.Popen) -> None:
    if proc.poll() is not None:
        return
    try:
        os.killpg(proc.pid, signal.SIGTERM)
    except (ProcessLookupError, PermissionError, OSError):
        proc.terminate()
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        try:
            os.killpg(proc.pid, signal.SIGKILL)
        except (ProcessLookupError, PermissionError, OSError):
            proc.kill()


def cinder_world(threads: int, repeats: int) -> dict:
    samples = []
    line = ""
    for i in range(repeats):
        t0 = time.perf_counter()
        proc = subprocess.Popen(
            [str(CINDER), "--threads", str(threads)],
            cwd=str(ROOT),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            start_new_session=True,
            bufsize=1,
        )
        ready = None
        assert proc.stdout is not None
        for raw in proc.stdout:
            if "world ready" in raw:
                ready = time.perf_counter() - t0
                line = raw.strip()
                break
        kill_tree(proc)
        if ready is None:
            raise RuntimeError("cinder never printed world ready")
        samples.append(ready)
        print(f"   cinder threads={threads} run={i+1}/{repeats} {ready*1000:.2f} ms  {line}", flush=True)
    return {
        "threads": threads,
        "line": line,
        "samples_ms": [x * 1000 for x in samples],
        "best_ms": min(samples) * 1000,
        "median_ms": statistics.median(samples) * 1000,
    }


def pumpkin_world(grid: int, threads: int, repeats: int) -> dict:
    if not PUMPKIN_GEN.exists():
        raise SystemExit(f"missing {PUMPKIN_GEN}; build pumpkin-gen first")
    samples = []
    line = ""
    for i in range(repeats):
        t0 = time.perf_counter()
        p = subprocess.run(
            [str(PUMPKIN_GEN), str(grid), str(threads)],
            capture_output=True,
            text=True,
            timeout=3600,
        )
        wall = time.perf_counter() - t0
        if p.returncode != 0:
            raise RuntimeError(f"pumpkin-gen failed:\n{p.stderr}\n{p.stdout}")
        line = p.stdout.strip().splitlines()[-1] if p.stdout.strip() else ""
        samples.append(wall)
        print(f"   pumpkin threads={threads} run={i+1}/{repeats} {wall*1000:.2f} ms  {line}", flush=True)
    return {
        "threads": threads,
        "grid": grid,
        "line": line,
        "samples_ms": [x * 1000 for x in samples],
        "best_ms": min(samples) * 1000,
        "median_ms": statistics.median(samples) * 1000,
    }


def main() -> int:
    BENCH.mkdir(parents=True, exist_ok=True)
    chunks = 1024
    print(f"== world gen {chunks} chunks (32x32)", flush=True)
    print("== cinder", flush=True)
    cinder = {}
    for t in (1, 4, 8, 16):
        cinder[str(t)] = cinder_world(t, repeats=3)
    print("== pumpkin", flush=True)
    pumpkin = {}
    for t in (1, 4, 8, 16):
        pumpkin[str(t)] = pumpkin_world(32, t, repeats=1 if t == 1 else 3)

    out = {"chunks": chunks, "cinder": cinder, "pumpkin": pumpkin}
    OUT.write_text(json.dumps(out, indent=2))

    md = []
    md.append("# World generation - Cinder vs Pumpkin")
    md.append("")
    md.append("Generated by `scripts/world_bench.py`; the full write-up is in "
              "[`WORLD.md`](WORLD.md).")
    md.append("")
    md.append("Same box, same grid: **32x32 = 1024 chunks** around origin.")
    md.append("")
    md.append("- **Cinder**: `./cinder --threads N` printed `world ready`, i.e. the whole "
              "vanilla 26.2 stage list (biomes, density, aquifers, ore veins, surface rules, "
              "carvers, vanilla features, lighting) into memory, then the listener comes up.")
    md.append("- **Pumpkin**: `pumpkin-gen 32 N`, `generate_single_chunk(..., Full)` - its own "
              "feature engine, in memory.")
    md.append("")
    md.append("| Threads | Cinder median | Cinder best | Pumpkin median | Pumpkin best | Pumpkin / Cinder (best) |")
    md.append("| ---: | ---: | ---: | ---: | ---: | ---: |")
    for t in ("1", "4", "8", "16"):
        c = cinder[t]
        p = pumpkin[t]
        md.append(
            f"| {t} | {c['median_ms'] / 1000:.2f} s | {c['best_ms'] / 1000:.2f} s | "
            f"{p['median_ms'] / 1000:.2f} s | {p['best_ms'] / 1000:.2f} s | "
            f"{p['best_ms'] / c['best_ms']:.2f}x |"
        )
    md.append("")
    c8 = cinder["8"]["best_ms"]
    p8 = pumpkin["8"]["best_ms"]
    c16 = cinder["16"]["best_ms"]
    p16 = pumpkin["16"]["best_ms"]
    md.append(
        f"On the thread counts both scale to (8): Cinder {c8 / 1000:.2f} s vs Pumpkin "
        f"{p8 / 1000:.2f} s, i.e. Pumpkin is **{c8 / p8:.2f}x faster**. At 16 threads "
        f"Cinder {c16 / 1000:.2f} s vs Pumpkin {p16 / 1000:.2f} s ({c16 / p16:.2f}x)."
    )
    md.append("")
    (BENCH / "PUMPKIN.md").write_text("\n".join(md) + "\n")
    print("\n".join(md), flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
