#!/usr/bin/env python3
"""Generate src/vanilla_block_tags.h: vanilla block tags as Cinder block-id bitmaps.

Tag membership comes from the server jar's data/minecraft/tags/block/*.json with
nested `#tag` entries resolved. The block-id mapping is read from the repo itself
(the B_* enum in src/vanilla_common.h zipped with the name table in
src/vanilla_gen.c), so this script can never drift from the palette.

    python3 bench/parity/gen_block_tags.py
"""
from __future__ import annotations

import json
import re
import sys
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]

JAR = Path("/home/nataxcan/dev/c2me-run/versions/26.2/server-26.2.jar")
OUT = ROOT / "src" / "vanilla_block_tags.h"

# Tags the feature code references directly (always emitted, even when no JSON
# string mentions them).
ALWAYS = [
    "minecraft:air",
    "minecraft:sculk_replaceable",
    "minecraft:sculk_replaceable_world_gen",
    "minecraft:base_stone_overworld",
    "minecraft:base_stone_nether",
    "minecraft:dirt",
    "minecraft:sand",
    "minecraft:terracotta",
    "minecraft:substrate_overworld",
    "minecraft:supports_vegetation",
    "minecraft:nylium",
    "minecraft:replaceable_by_trees",
    "minecraft:features_cannot_replace",
    "minecraft:lush_ground_replaceable",
    "minecraft:moss_replaceable",
    "minecraft:azalea_root_replaceable",
    "minecraft:azalea_grows_on",
    "minecraft:mangrove_logs_can_grow_through",
    "minecraft:mangrove_roots_can_grow_through",
    "minecraft:stone_ore_replaceables",
    "minecraft:deepslate_ore_replaceables",
    "minecraft:dripstone_replaceable_blocks",
    "minecraft:geode_invalid_blocks",
    "minecraft:ice_spike_replaceable",
    "minecraft:forest_rock_can_place_on",
    "minecraft:lava_pool_stone_cannot_replace",
    "minecraft:huge_brown_mushroom_can_place_on",
    "minecraft:huge_red_mushroom_can_place_on",
    "minecraft:beneath_tree_podzol_replaceable",
    "minecraft:cannot_replace_below_tree_trunk",
    "minecraft:sulfur_spike_replaceable_blocks",
]


def palette() -> dict[str, int]:
    """name -> id, read from the enum and the name table (order-checked)."""
    header = (ROOT / "src" / "vanilla_common.h").read_text()
    body = header[header.index("B_AIR = 0") : header.index("B_COUNT")]
    ids = ["B_AIR"] + [
        i for i in re.findall(r"^\s*(B_[A-Z0-9_]+),?\s*$", body, re.M) if i != "B_AIR"
    ]
    gen = (ROOT / "src" / "vanilla_gen.c").read_text()
    start = gen.index("static const char *names[B_COUNT] = {")
    end = gen.index("\n};", start)
    names = re.findall(r'"(minecraft:[a-z_0-9]+)"', gen[start:end])
    if len(ids) != len(names):
        raise SystemExit(f"palette misaligned: {len(ids)} ids vs {len(names)} names")
    return {name: i for i, name in enumerate(names)}


def main() -> int:
    name_to_id = palette()
    with zipfile.ZipFile(JAR) as z:
        tags: dict[str, list[str]] = {}
        for entry in z.namelist():
            if not entry.startswith("data/minecraft/tags/block/") or not entry.endswith(".json"):
                continue
            raw = json.loads(z.read(entry))
            tag = "minecraft:" + entry[len("data/minecraft/tags/block/") : -len(".json")]
            tags[tag] = raw.get("values", [])

    resolved: dict[str, list[str]] = {}

    def resolve(tag: str, seen: set[str]) -> list[str]:
        if tag in resolved:
            return resolved[tag]
        if tag in seen:
            return []
        seen.add(tag)
        out: list[str] = []
        for value in tags.get(tag, []):
            if isinstance(value, dict):
                value = value.get("id", "")
            if value.startswith("#"):
                out.extend(resolve(value[1:], seen))
            else:
                out.append(value)
        resolved[tag] = out
        return out

    for tag in tags:
        resolve(tag, set())

    embed = (ROOT / "src" / "vanilla" / "embed.h").read_text(encoding="utf-8", errors="replace")
    wanted = set(ALWAYS)
    for t in re.findall(r"#minecraft:([a-z_/]+)", embed):
        wanted.add("minecraft:" + t)
    for t in re.findall(r'tag\\": \\"minecraft:([a-z_/]+)', embed):
        wanted.add("minecraft:" + t)
    for t in re.findall(r'tag: minecraft:([a-z_/]+)', embed):
        wanted.add("minecraft:" + t)

    known = sorted(t for t in wanted if t in resolved)
    unknown = sorted(t for t in wanted if t not in resolved)

    lines = [
        "/* Auto-generated by bench/parity/gen_block_tags.py. Do not edit. */",
        "/* Vanilla block tags as Cinder B_* id lists (nested tags resolved). */",
        "#pragma once",
        "",
    ]
    emitted = []
    for i, tag in enumerate(known):
        ids = sorted({name_to_id[v] for v in resolved[tag] if v in name_to_id})
        members = ", ".join(str(x) for x in ids) if ids else "0"
        lines.append(f"/* {tag} */")
        lines.append(f"static const int TAG_{i}_IDS[] = {{{members}}};")
        emitted.append((tag, len(ids)))
    lines.append("")
    lines.append("typedef struct { const char *tag; const int *ids; int count; } BlockTagEnt;")
    lines.append("static const BlockTagEnt BLOCK_TAGS[] = {")
    for i, (tag, count) in enumerate(emitted):
        lines.append(f'  {{"{tag}", TAG_{i}_IDS, {count}}},')
    lines.append("};")
    lines.append("#define BLOCK_TAG_COUNT (int)(sizeof BLOCK_TAGS / sizeof BLOCK_TAGS[0])")
    lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT}: {len(emitted)} tags, palette {len(name_to_id)} blocks")
    for tag, count in emitted:
        print(f"  {count:4d} blocks  {tag}")
    if unknown:
        print(f"tags referenced but not in the jar ({len(unknown)}): {unknown[:8]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
