#!/usr/bin/env python3
"""Generate src/vanilla_biomes.h from the vanarilla multi-noise parameter dump.

Input : bench/parity/biome_params.json (produced by bench/parity/run.sh, which
        calls the vanilla OverworldBiomeBuilder through the real server jar -
        the authoritative, in-order parameter list).
Output: src/vanilla_biomes.h - the parameter table plus the biome name table,
        so the C generator picks biomes exactly like vanilla does.

The name -> enum mapping below is the only hand-maintained part; it must match
the BIO_* enum order in src/vanilla_common.h.
"""
from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]

# BIO_* enum order from src/vanilla_common.h -> vanilla resource path.
BIOME_ENUM = [
    ("BIO_OCEAN", "ocean"),
    ("BIO_DEEP_OCEAN", "deep_ocean"),
    ("BIO_FROZEN_OCEAN", "frozen_ocean"),
    ("BIO_DEEP_FROZEN_OCEAN", "deep_frozen_ocean"),
    ("BIO_COLD_OCEAN", "cold_ocean"),
    ("BIO_DEEP_COLD_OCEAN", "deep_cold_ocean"),
    ("BIO_LUKEWARM_OCEAN", "lukewarm_ocean"),
    ("BIO_DEEP_LUKEWARM_OCEAN", "deep_lukewarm_ocean"),
    ("BIO_WARM_OCEAN", "warm_ocean"),
    ("BIO_RIVER", "river"),
    ("BIO_FROZEN_RIVER", "frozen_river"),
    ("BIO_BEACH", "beach"),
    ("BIO_SNOWY_BEACH", "snowy_beach"),
    ("BIO_STONY_SHORE", "stony_shore"),
    ("BIO_MUSHROOM", "mushroom_fields"),
    ("BIO_PLAINS", "plains"),
    ("BIO_SUNFLOWER", "sunflower_plains"),
    ("BIO_FOREST", "forest"),
    ("BIO_FLOWER_FOREST", "flower_forest"),
    ("BIO_BIRCH", "birch_forest"),
    ("BIO_OLD_BIRCH", "old_growth_birch_forest"),
    ("BIO_DARK_FOREST", "dark_forest"),
    ("BIO_TAIGA", "taiga"),
    ("BIO_SNOWY_TAIGA", "snowy_taiga"),
    ("BIO_OLD_PINE", "old_growth_pine_taiga"),
    ("BIO_OLD_SPRUCE", "old_growth_spruce_taiga"),
    ("BIO_SAVANNA", "savanna"),
    ("BIO_SAVANNA_PLATEAU", "savanna_plateau"),
    ("BIO_WINDSWEPT_SAVANNA", "windswept_savanna"),
    ("BIO_JUNGLE", "jungle"),
    ("BIO_SPARSE_JUNGLE", "sparse_jungle"),
    ("BIO_BAMBOO_JUNGLE", "bamboo_jungle"),
    ("BIO_DESERT", "desert"),
    ("BIO_SWAMP", "swamp"),
    ("BIO_MANGROVE", "mangrove_swamp"),
    ("BIO_BADLANDS", "badlands"),
    ("BIO_WOODED_BADLANDS", "wooded_badlands"),
    ("BIO_ERODED_BADLANDS", "eroded_badlands"),
    ("BIO_MEADOW", "meadow"),
    ("BIO_CHERRY", "cherry_grove"),
    ("BIO_GROVE", "grove"),
    ("BIO_SNOWY_SLOPES", "snowy_slopes"),
    ("BIO_JAGGED_PEAKS", "jagged_peaks"),
    ("BIO_FROZEN_PEAKS", "frozen_peaks"),
    ("BIO_STONY_PEAKS", "stony_peaks"),
    ("BIO_SNOWY_PLAINS", "snowy_plains"),
    ("BIO_ICE_SPIKES", "ice_spikes"),
    ("BIO_WINDSWEPT_HILLS", "windswept_hills"),
    ("BIO_WINDSWEPT_GRAVEL", "windswept_gravelly_hills"),
    ("BIO_WINDSWEPT_FOREST", "windswept_forest"),
    ("BIO_DRIPSTONE", "dripstone_caves"),
    ("BIO_LUSH", "lush_caves"),
    ("BIO_SULFUR", "sulfur_caves"),
    ("BIO_DEEP_DARK", "deep_dark"),
    ("BIO_PALE_GARDEN", "pale_garden"),
]

PARAMS = [
    "temperature",
    "humidity",
    "continentalness",
    "erosion",
    "depth",
    "weirdness",
]


def main() -> int:
    data = json.loads((HERE / "biome_params.json").read_text())
    entries = data["entries"]
    name_to_enum = {f"minecraft:{name}": symbol for symbol, name in BIOME_ENUM}

    unknown = sorted({e["biome"] for e in entries if e["biome"] not in name_to_enum})
    if unknown:
        raise SystemExit(f"biome names missing from the enum table: {unknown}")

    lines = [
        "/* Auto-generated by bench/parity/gen_biome_table.py. Do not edit. */",
        "/* Vanilla OverworldBiomeBuilder parameter list, in call order. */",
        "#pragma once",
        "",
        "static const char *const BIOME_NAMES[BIO_COUNT] = {",
    ]
    for symbol, name in BIOME_ENUM:
        lines.append(f'  [ {symbol} ] = "minecraft:{name}",')
    lines.append("};")
    lines.append("")
    lines.append(f"#define BIOME_PARAM_COUNT {len(entries)}")
    lines.append("static const BiomeParamPoint BIOME_PARAMS[BIOME_PARAM_COUNT] = {")
    for e in entries:
        vals = []
        for key in PARAMS:
            lo, hi = e[key]
            vals.append(f"{{{lo}, {hi}}}")
        offset = e["offset"]
        lines.append(f"  {{{name_to_enum[e['biome']]}, {', '.join(vals)}, {offset}}},")
    lines.append("};")
    lines.append("")

    out = ROOT / "src" / "vanilla_biomes.h"
    out.write_text("\n".join(lines))
    print(f"wrote {out}: {len(entries)} parameter points, {len(BIOME_ENUM)} biomes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
