/* Auto-generated by bench/parity/gen_block_tags.py. Do not edit. */
/* Vanilla block tags as Cinder B_* id lists (nested tags resolved). */
#pragma once

/* minecraft:air */
static const int TAG_0_IDS[] = {0, 131, 179};
/* minecraft:azalea_grows_on */
static const int TAG_1_IDS[] = {2, 3, 7, 8, 36, 37, 41, 42, 65, 66, 67, 68, 106, 132, 133, 134, 135, 136, 137, 138, 142, 147};
/* minecraft:azalea_root_replaceable */
static const int TAG_2_IDS[] = {1, 2, 3, 7, 8, 10, 11, 20, 28, 29, 30, 31, 36, 37, 41, 42, 65, 66, 67, 68, 106, 132, 133, 134, 135, 136, 137, 138, 142};
/* minecraft:base_stone_nether */
static const int TAG_3_IDS[] = {0};
/* minecraft:base_stone_overworld */
static const int TAG_4_IDS[] = {1, 20, 28, 29, 30, 31};
/* minecraft:beneath_tree_podzol_replaceable */
static const int TAG_5_IDS[] = {2, 3, 36, 37, 65, 66, 67, 106, 138, 142};
/* minecraft:cannot_replace_below_tree_trunk */
static const int TAG_6_IDS[] = {2, 36, 37, 65, 67, 106, 138, 142};
/* minecraft:deepslate_ore_replaceables */
static const int TAG_7_IDS[] = {20, 31};
/* minecraft:dirt */
static const int TAG_8_IDS[] = {2, 67, 138};
/* minecraft:dripstone_replaceable_blocks */
static const int TAG_9_IDS[] = {1, 20, 28, 29, 30, 31};
/* minecraft:features_cannot_replace */
static const int TAG_10_IDS[] = {4, 126, 151};
/* minecraft:forest_rock_can_place_on */
static const int TAG_11_IDS[] = {1, 2, 3, 20, 28, 29, 30, 31, 36, 37, 65, 66, 67, 106, 138, 142};
/* minecraft:geode_invalid_blocks */
static const int TAG_12_IDS[] = {4, 5, 6, 38, 39, 81};
/* minecraft:huge_brown_mushroom_can_place_on */
static const int TAG_13_IDS[] = {2, 3, 36, 37, 65, 66, 67, 106, 138, 142};
/* minecraft:huge_red_mushroom_can_place_on */
static const int TAG_14_IDS[] = {2, 3, 36, 37, 65, 66, 67, 106, 138, 142};
/* minecraft:ice_spike_replaceable */
static const int TAG_15_IDS[] = {2, 3, 36, 37, 39, 65, 66, 67, 68, 106, 138, 142};
/* minecraft:lava_pool_stone_cannot_replace */
static const int TAG_16_IDS[] = {4, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 126, 151, 163, 165, 169, 170};
/* minecraft:lush_ground_replaceable */
static const int TAG_17_IDS[] = {1, 2, 3, 7, 10, 11, 20, 28, 29, 30, 31, 36, 37, 65, 66, 67, 87, 88, 106, 138, 142};
/* minecraft:mangrove_logs_can_grow_through */
static const int TAG_18_IDS[] = {37, 57, 58, 128, 142, 157, 160, 161};
/* minecraft:mangrove_roots_can_grow_through */
static const int TAG_19_IDS[] = {37, 40, 128, 142, 157, 160, 161};
/* minecraft:moss_replaceable */
static const int TAG_20_IDS[] = {1, 2, 3, 20, 28, 29, 30, 31, 36, 37, 65, 66, 67, 87, 88, 106, 138, 142};
/* minecraft:nether_carver_replaceables */
static const int TAG_21_IDS[] = {1, 2, 3, 20, 28, 29, 30, 31, 36, 37, 65, 66, 67, 106, 138, 141, 142};
/* minecraft:nylium */
static const int TAG_22_IDS[] = {0};
/* minecraft:overworld_carver_replaceables */
static const int TAG_23_IDS[] = {1, 2, 3, 5, 7, 8, 9, 10, 13, 14, 20, 22, 23, 28, 29, 30, 31, 32, 36, 37, 38, 40, 41, 42, 65, 66, 67, 68, 76, 77, 106, 112, 119, 132, 133, 134, 135, 136, 137, 138, 139, 140, 142, 147};
/* minecraft:replaceable_by_trees */
static const int TAG_24_IDS[] = {5, 44, 46, 48, 50, 52, 54, 56, 58, 63, 64, 72, 73, 74, 78, 80, 82, 85, 89, 90, 91, 93, 94, 97, 98, 99, 100, 104, 105, 107, 109, 111, 114, 115, 116, 121, 123, 124, 153, 157, 163, 165, 170, 171, 174, 177};
/* minecraft:sand */
static const int TAG_25_IDS[] = {7, 8, 147};
/* minecraft:sculk_replaceable */
static const int TAG_26_IDS[] = {1, 2, 3, 7, 8, 9, 10, 11, 20, 28, 29, 30, 31, 32, 33, 35, 36, 37, 42, 65, 66, 67, 106, 119, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142};
/* minecraft:sculk_replaceable_world_gen */
static const int TAG_27_IDS[] = {1, 2, 3, 7, 8, 9, 10, 11, 20, 28, 29, 30, 31, 32, 33, 35, 36, 37, 42, 65, 66, 67, 106, 119, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142};
/* minecraft:stone_ore_replaceables */
static const int TAG_28_IDS[] = {1, 28, 29, 30};
/* minecraft:substrate_overworld */
static const int TAG_29_IDS[] = {2, 3, 36, 37, 65, 66, 67, 106, 138, 142};
/* minecraft:sulfur_spike_replaceable_blocks */
static const int TAG_30_IDS[] = {119, 140};
/* minecraft:supports_vegetation */
static const int TAG_31_IDS[] = {2, 3, 36, 37, 65, 66, 67, 106, 138, 142, 152};
/* minecraft:terracotta */
static const int TAG_32_IDS[] = {42, 132, 133, 134, 135, 136, 137};

typedef struct { const char *tag; const int *ids; int count; } BlockTagEnt;
static const BlockTagEnt BLOCK_TAGS[] = {
  {"minecraft:air", TAG_0_IDS, 3},
  {"minecraft:azalea_grows_on", TAG_1_IDS, 22},
  {"minecraft:azalea_root_replaceable", TAG_2_IDS, 29},
  {"minecraft:base_stone_nether", TAG_3_IDS, 0},
  {"minecraft:base_stone_overworld", TAG_4_IDS, 6},
  {"minecraft:beneath_tree_podzol_replaceable", TAG_5_IDS, 10},
  {"minecraft:cannot_replace_below_tree_trunk", TAG_6_IDS, 8},
  {"minecraft:deepslate_ore_replaceables", TAG_7_IDS, 2},
  {"minecraft:dirt", TAG_8_IDS, 3},
  {"minecraft:dripstone_replaceable_blocks", TAG_9_IDS, 6},
  {"minecraft:features_cannot_replace", TAG_10_IDS, 3},
  {"minecraft:forest_rock_can_place_on", TAG_11_IDS, 16},
  {"minecraft:geode_invalid_blocks", TAG_12_IDS, 6},
  {"minecraft:huge_brown_mushroom_can_place_on", TAG_13_IDS, 10},
  {"minecraft:huge_red_mushroom_can_place_on", TAG_14_IDS, 10},
  {"minecraft:ice_spike_replaceable", TAG_15_IDS, 12},
  {"minecraft:lava_pool_stone_cannot_replace", TAG_16_IDS, 23},
  {"minecraft:lush_ground_replaceable", TAG_17_IDS, 21},
  {"minecraft:mangrove_logs_can_grow_through", TAG_18_IDS, 8},
  {"minecraft:mangrove_roots_can_grow_through", TAG_19_IDS, 7},
  {"minecraft:moss_replaceable", TAG_20_IDS, 18},
  {"minecraft:nether_carver_replaceables", TAG_21_IDS, 17},
  {"minecraft:nylium", TAG_22_IDS, 0},
  {"minecraft:overworld_carver_replaceables", TAG_23_IDS, 44},
  {"minecraft:replaceable_by_trees", TAG_24_IDS, 46},
  {"minecraft:sand", TAG_25_IDS, 3},
  {"minecraft:sculk_replaceable", TAG_26_IDS, 35},
  {"minecraft:sculk_replaceable_world_gen", TAG_27_IDS, 35},
  {"minecraft:stone_ore_replaceables", TAG_28_IDS, 4},
  {"minecraft:substrate_overworld", TAG_29_IDS, 10},
  {"minecraft:sulfur_spike_replaceable_blocks", TAG_30_IDS, 2},
  {"minecraft:supports_vegetation", TAG_31_IDS, 11},
  {"minecraft:terracotta", TAG_32_IDS, 7},
};
#define BLOCK_TAG_COUNT (int)(sizeof BLOCK_TAGS / sizeof BLOCK_TAGS[0])
